method: random
metric:
  goal: minimize
  name: val_loss
parameters:
  attention:
    value: false
  batch_size:
    value: 5
  dim:
    value: 3
  in_channels:
    value: 1
  learning_rate:
    distribution: uniform
    max: 0.01
    min: 1.0e-05
  loss_alpha:
    distribution: uniform
    max: 1.0
    min: 0.01
  loss_gamma:
    value: 1.0
  max_epochs:
    value: 50
  n_blocks:
    values:
    - 3
    - 4
    - 5
    - 6
  out_channels:
    value: 4
  start_filters:
    values:
    - 8
    - 16
    - 32
